Update README.md
Vita-App/Vita pull request #168
Opened 2023-03-05 16:45 UTC by Code1705

committed the changes , please could you merge my pr?

2023-03-06 07:33 UTC, Code1705 commented
just could you merge my PR please , after reviewing.

2023-03-06 07:55 UTC, Lalit3716 requested changes
Please do these changes, Thanks!

2023-03-06 07:55 UTC, Lalit3716 commented on README.md
> +* [Lalit Kumar Singh](https://github.com/harshita214)
```suggestion
If you have any feedback or suggestions please reach out to: 
* [Lalit Kumar Singh](https://github.com/Lalit3716) 
```

2023-03-06 07:55 UTC, Lalit3716 commented on README.md
> +Or you can create a  <a href="https://github.com/aman34503/harshita214/issues">issue</a> and mention there , which new features or extension can make this Project more good.
Correct the url in `href` here

2023-03-06 07:55 UTC, Lalit3716 commented on README.md
> +
Remove this section

2023-03-06 09:12 UTC, Code1705 commented
As per you require changes are made , kindly merge my pr

2023-03-07 02:15 UTC, Code1705 commented
I have done the changes , please could you merge it with the label of jwoc

2023-03-07 09:09 UTC, Lalit3716 requested changes
Don't make changes to `index.css` in this pull request as it's not really related to improving documentation.
Also please do the change I have mentioned thanks!

2023-03-07 09:09 UTC, Lalit3716 commented on README.md
> +Or you can create a  <a href="https://github.com/Vita-App/Vita/issues">issue</a> and mention there , which new features or extension can make this Project more good.
```suggestion
If you have any feedback or suggestions you can create an  <a href="https://github.com/Vita-App/Vita/issues">issue</a> and mention there , which new features or extension can make this Project more good.
```

2023-03-07 09:51 UTC, Code1705 commented
see now is it ok?

2023-03-07 11:39 UTC, Lalit3716 requested changes
Please undo all the changes you did in `index.css`

2023-03-07 11:39 UTC, Lalit3716 commented on README.md
> -
Don't remove this section just make some changes I told you to make in previous review

2023-03-07 17:11 UTC, Code1705 commented
now is it ok?
could you check please?

2023-03-08 05:36 UTC, Code1705 commented
could you merge my PR?

2023-03-09 05:18 UTC, Code1705 commented
as per your instructions , changes are made now merge my pr

2023-03-12 13:50 UTC, closed without merging

2023-03-12 13:53 UTC, Lalit3716 commented
@Code1705 Can you reopen this PR idk but it somehow got closed ?

2023-03-13 04:35 UTC, Code1705 commented
As you told I opened the new issue as update readme , now you can label it under Jwoc and assign me.